#Dependencies
markdown:   kramdown

#Permalinks
permalink:  /blog/:year/:month/:day/:title
relative_permalinks:    false

#Setup
url:    Naruto8.github.io

description: >
    My first site using Jekyll.

author:
    name:   'Rohith Mukku'

github:
    repo:   https://github.com/Naruto8

future: true
